# Generated by Django 3.2.4 on 2021-06-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.il')),
            ],
        ),
        migrations.CreateModel(
            name='Usta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.CharField(blank=True, max_length=100, null=True)),
                ('il', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.il')),
                ('ilce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.ilce')),
            ],
        ),
    ]
