# Generated by Django 3.2.4 on 2021-06-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='usta',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='usta',
            name='desc',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usta',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usta',
            name='telefon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usta',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usta',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.category'),
        ),
    ]
