# Generated by Django 3.2.4 on 2021-06-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210611_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usta2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('telefon', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField(max_length=1000, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.category')),
                ('il', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.il')),
                ('ilce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.ilce')),
            ],
        ),
    ]
