# Generated by Django 3.2.4 on 2021-06-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usta',
            name='image',
            field=models.ImageField(default='ananas.jpg', upload_to='profile_images'),
        ),
    ]
