# Generated by Django 3.2.4 on 2021-06-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_usta_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usta',
            name='image',
        ),
    ]
