# Generated by Django 3.2.4 on 2021-06-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_usta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usta',
            name='image',
            field=models.ImageField(default='ananas.jpg', upload_to='profile_images'),
        ),
    ]
